// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OvirtPlatform oVirt platform specific configuration upon which to perform the installation
//
// swagger:model ovirt_platform
type OvirtPlatform struct {

	// The oVirt cluster ID.
	// Required: true
	// Format: uuid
	ClusterID *strfmt.UUID `json:"cluster_id"`

	// Verify oVirt engine certificate.
	Insecure *bool `json:"insecure,omitempty"`

	// The oVirt network the VMs will be attached to.
	// Required: true
	NetworkName *string `json:"network_name"`

	// The password for the oVirt user name.
	// Required: true
	// Format: password
	Password *strfmt.Password `json:"password"`

	// The oVirt storage domain ID.
	// Required: true
	// Format: uuid
	StorageDomainID *strfmt.UUID `json:"storage_domain_id"`

	// The oVirt API URL.
	// Required: true
	URL *string `json:"url"`

	// The user name to use to connect to the oVirt instance.
	// Required: true
	Username *string `json:"username"`

	// The oVirt VNIC profile ID.
	// Required: true
	// Format: uuid
	VnicProfileID *strfmt.UUID `json:"vnic_profile_id"`
}

// Validate validates this ovirt platform
func (m *OvirtPlatform) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageDomainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVnicProfileID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OvirtPlatform) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("cluster_id", "body", m.ClusterID); err != nil {
		return err
	}

	if err := validate.FormatOf("cluster_id", "body", "uuid", m.ClusterID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validateNetworkName(formats strfmt.Registry) error {

	if err := validate.Required("network_name", "body", m.NetworkName); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.FormatOf("password", "body", "password", m.Password.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validateStorageDomainID(formats strfmt.Registry) error {

	if err := validate.Required("storage_domain_id", "body", m.StorageDomainID); err != nil {
		return err
	}

	if err := validate.FormatOf("storage_domain_id", "body", "uuid", m.StorageDomainID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

func (m *OvirtPlatform) validateVnicProfileID(formats strfmt.Registry) error {

	if err := validate.Required("vnic_profile_id", "body", m.VnicProfileID); err != nil {
		return err
	}

	if err := validate.FormatOf("vnic_profile_id", "body", "uuid", m.VnicProfileID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OvirtPlatform) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OvirtPlatform) UnmarshalBinary(b []byte) error {
	var res OvirtPlatform
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
